### ISSUE TITLE
Error while launching bot

### ISSUE THREAD

**Issue by roblox-afk** [Redon-Tech/Roblox-Purchasing-Hub#13]
There is a error when i run the command

Traceback (most recent call last):
  File "C:\Users\Name\Desktop\WoodMartHub\Hub\BOT\launcher.py", line 10, in <module>
    BotBase.run(version, False)
  File "C:\Python310\lib\site-packages\nextcord\client.py", line 699, in run
    loop = self.loop
AttributeError: 'str' object has no attribute 'loop'

**Comment by parker02311** [comment]
Could you run

```
pip install -U -r BOT/requirements.txt
```

For me and tell me if the error is still happening

**Comment by roblox-afk** [comment]
it is giving this:

python BOT/launcher.py
C:\Python310\lib\site-packages\nextcord\health_check.py:20: DistributionWarning: discord.py is installed which is incompatible with nextcord. Please remove this library by using `pip3 uninstall discord.py`
  warn(message, DistributionWarning, stacklevel=0)
C:\Python310\lib\site-packages\nextcord\health_check.py:20: DistributionWarning: discord is installed which is incompatible with nextcord. Please remove this library by using `pip3 uninstall discord`
  warn(message, DistributionWarning, stacklevel=0)
Traceback (most recent call last):
  File "C:\Users\Name\Desktop\WoodMartHub\Hub\BOT\launcher.py", line 10, in <module>
    BotBase.run(version, False)
  File "C:\Python310\lib\site-packages\nextcord\client.py", line 699, in run
    loop = self.loop
AttributeError: 'str' object has no attribute 'loop'

**Comment by parker02311** [comment]
Ok run

```
pip uninstall discord.py discord
```
